/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taller;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.JComboBox;
import javax.swing.JPanel;

/**
 *
 * @author EDWIN
 */
public class simulacion extends javax.swing.JFrame {

    /**
     * Creates new form simulacion
     */
    Fondo fondo= new Fondo();
    informacion1 inf= new informacion1();
    acerca_de ac=new acerca_de();
   simulador sim=new simulador();
   private VentanaSimulacion simu;
    
    
    public simulacion() {
     initComponents();
     this.add(fondo,BorderLayout.CENTER);
     this.pack();
     ATRAS.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        INFORMACION = new javax.swing.JButton();
        SIMULACION = new javax.swing.JButton();
        SALIR = new javax.swing.JButton();
        ACERCA_DE = new javax.swing.JButton();
        ATRAS = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        INFORMACION.setBackground(new java.awt.Color(0, 153, 204));
        INFORMACION.setText("INFORMACION");
        INFORMACION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INFORMACIONActionPerformed(evt);
            }
        });

        SIMULACION.setBackground(new java.awt.Color(0, 153, 204));
        SIMULACION.setText("SIMULACION");
        SIMULACION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIMULACIONActionPerformed(evt);
            }
        });

        SALIR.setBackground(new java.awt.Color(0, 153, 204));
        SALIR.setText(" SALIR");
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });

        ACERCA_DE.setBackground(new java.awt.Color(0, 153, 204));
        ACERCA_DE.setText(" ACERCA DE");
        ACERCA_DE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACERCA_DEActionPerformed(evt);
            }
        });

        ATRAS.setText(" ATRAS");
        ATRAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ATRASActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SIMULACION, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ACERCA_DE, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SALIR, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(INFORMACION, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ATRAS, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 264, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(225, 225, 225))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ATRAS, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(SIMULACION, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(INFORMACION, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ACERCA_DE, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(SALIR, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
       //this.dispose();
       System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_SALIRActionPerformed

    private void INFORMACIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INFORMACIONActionPerformed
        fondo.setVisible(false);
        INFORMACION.setVisible(false);
        ACERCA_DE.setVisible(false);
        SIMULACION.setVisible(false);
        SALIR.setVisible(false);
        ATRAS.setVisible(true);
        
        inf.setVisible(true);
        this.add(inf, BorderLayout.CENTER);
        this.pack();
        this.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_INFORMACIONActionPerformed

    private void ATRASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ATRASActionPerformed
        fondo.setVisible(true);
        INFORMACION.setVisible(true);
        ACERCA_DE.setVisible(true);
        SIMULACION.setVisible(true);
        SALIR.setVisible(true);
        ATRAS.setVisible(false);
        
        inf.setVisible(false);
        this.add(inf, BorderLayout.CENTER);
        this.pack();
        this.setExtendedState(MAXIMIZED_BOTH);

        // TODO add your handling code here:
    }//GEN-LAST:event_ATRASActionPerformed

    private void ACERCA_DEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACERCA_DEActionPerformed
        fondo.setVisible(false);
        INFORMACION.setVisible(false);
        ACERCA_DE.setVisible(false);
        SIMULACION.setVisible(false);
        SALIR.setVisible(false);
        ATRAS.setVisible(true);
        
        ac.setVisible(true);
        this.add(ac, BorderLayout.CENTER);
        this.pack();
        this.setExtendedState(MAXIMIZED_BOTH);
           // TODO add your handling code here:
    }//GEN-LAST:event_ACERCA_DEActionPerformed

    private void SIMULACIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIMULACIONActionPerformed

        // TODO add your handling code here:
        //this.setVisible(false);
        //sim.setVisible(true);
         int gastos = Integer.parseInt(jComboBox2.getSelectedItem().toString());//cb_gastos nº empleados
			    int investigaciones =1;
			      int llamadas = Integer.parseInt(jComboBox3.getSelectedItem().toString());
			      int siniestros = Integer.parseInt(jComboBox1.getSelectedItem().toString());
				simu=new VentanaSimulacion(gastos,investigaciones,llamadas,siniestros);			
			    simu.setVisible(true);
        
       
       // sim.simulacionMenu(MENU,getObj());
    }//GEN-LAST:event_SIMULACIONActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(simulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(simulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(simulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(simulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                simulacion s= new simulacion();
                 s.setExtendedState(MAXIMIZED_BOTH);
                 
                s.setVisible(true);
            }
        });
    }
    

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACERCA_DE;
    private javax.swing.JButton ATRAS;
    private javax.swing.JButton INFORMACION;
    private javax.swing.JButton SALIR;
    private javax.swing.JButton SIMULACION;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    // End of variables declaration//GEN-END:variables
}
